var blogs = [
	{
		title: 'The Beauty of Nature',
		intro: 'Nature offers us a sanctuary from the chaos of the modern world...',
		image: 'https://source.unsplash.com/random/400x200?nature',
		author: 'John Doe',
		date: '2024-01-01',
		content: 'Full content of the blog post goes here.',
	},
	{
		title: 'The Beauty of Nature',
		intro: 'Nature offers us a sanctuary from the chaos of the modern world...',
		image: 'https://source.unsplash.com/random/400x200?nature',
		author: 'John Doe',
		date: '2024-01-01',
		content: 'Full content of the blog post goes here.',
	},
	{
		title: 'Tech Innovations in 2024',
		intro: 'The tech industry continues to evolve at a rapid pace...',
		image: 'https://source.unsplash.com/random/400x200?tech',
		author: 'Jane Smith',
		date: '2024-02-15',
		content: 'Full content of the blog post goes here.',
	},
	{
		title: 'The Beauty of Nature',
		intro: 'Nature offers us a sanctuary from the chaos of the modern world...',
		image: 'https://source.unsplash.com/random/400x200?nature',
		author: 'John Doe',
		date: '2024-01-01',
		content: 'Full content of the blog post goes here.',
	},
	{
		title: 'The Beauty of Nature',
		intro: 'Nature offers us a sanctuary from the chaos of the modern world...',
		image: 'https://source.unsplash.com/random/400x200?nature',
		author: 'John Doe',
		date: '2024-01-01',
		content: 'Full content of the blog post goes here.',
	},
	{
		title: 'Tech Innovations in 2024',
		intro: 'The tech industry continues to evolve at a rapid pace...',
		image: 'https://source.unsplash.com/random/400x200?tech',
		author: 'Jane Smith',
		date: '2024-02-15',
		content: 'Full content of the blog post goes here.',
	},
	{
		title: 'The Beauty of Nature',
		intro: 'Nature offers us a sanctuary from the chaos of the modern world...',
		image: 'https://source.unsplash.com/random/400x200?nature',
		author: 'John Doe',
		date: '2024-01-01',
		content: 'Full content of the blog post goes here.',
	},
	{
		title: 'The Beauty of Nature',
		intro: 'Nature offers us a sanctuary from the chaos of the modern world...',
		image: 'https://source.unsplash.com/random/400x200?nature',
		author: 'John Doe',
		date: '2024-01-01',
		content: 'Full content of the blog post goes here.',
	},
	{
		title: 'Tech Innovations in 2024',
		intro: 'The tech industry continues to evolve at a rapid pace...',
		image: 'https://source.unsplash.com/random/400x200?tech',
		author: 'Jane Smith',
		date: '2024-02-15',
		content: 'Full content of the blog post goes here.',
	},
	{
		title: 'The Beauty of Nature',
		intro: 'Nature offers us a sanctuary from the chaos of the modern world...',
		image: 'https://source.unsplash.com/random/400x200?nature',
		author: 'John Doe',
		date: '2024-01-01',
		content: 'Full content of the blog post goes here.',
	},
	{
		title: 'The Beauty of Nature',
		intro: 'Nature offers us a sanctuary from the chaos of the modern world...',
		image: 'https://source.unsplash.com/random/400x200?nature',
		author: 'John Doe',
		date: '2024-01-01',
		content: 'Full content of the blog post goes here.',
	},
	{
		title: 'The Beauty of Nature',
		intro: 'Nature offers us a sanctuary from the chaos of the modern world...',
		image: 'https://source.unsplash.com/random/400x200?nature',
		author: 'John Doe',
		date: '2024-01-01',
		content: 'Full content of the blog post goes here.',
	},
	{
		title: 'Tech Innovations in 2024',
		intro: 'The tech industry continues to evolve at a rapid pace...',
		image: 'https://source.unsplash.com/random/400x200?tech',
		author: 'Jane Smith',
		date: '2024-02-15',
		content: 'Full content of the blog post goes here.',
	},
	{
		title: 'The Beauty of Nature',
		intro: 'Nature offers us a sanctuary from the chaos of the modern world...',
		image: 'https://source.unsplash.com/random/400x200?nature',
		author: 'John Doe',
		date: '2024-01-01',
		content: 'Full content of the blog post goes here.',
	},
	{
		title: 'The Beauty of Nature',
		intro: 'Nature offers us a sanctuary from the chaos of the modern world...',
		image: 'https://source.unsplash.com/random/400x200?nature',
		author: 'John Doe',
		date: '2024-01-01',
		content: 'Full content of the blog post goes here.',
	},
	{
		title: 'Tech Innovations in 2024',
		intro: 'The tech industry continues to evolve at a rapid pace...',
		image: 'https://source.unsplash.com/random/400x200?tech',
		author: 'Jane Smith',
		date: '2024-02-15',
		content: 'Full content of the blog post goes here.',
	},
	{
		title: 'The Beauty of Nature',
		intro: 'Nature offers us a sanctuary from the chaos of the modern world...',
		image: 'https://source.unsplash.com/random/400x200?nature',
		author: 'John Doe',
		date: '2024-01-01',
		content: 'Full content of the blog post goes here.',
	},
	{
		title: 'The Beauty of Nature',
		intro: 'Nature offers us a sanctuary from the chaos of the modern world...',
		image: 'https://source.unsplash.com/random/400x200?nature',
		author: 'John Doe',
		date: '2024-01-01',
		content: 'Full content of the blog post goes here.',
	},
	{
		title: 'Tech Innovations in 2024',
		intro: 'The tech industry continues to evolve at a rapid pace...',
		image: 'https://source.unsplash.com/random/400x200?tech',
		author: 'Jane Smith',
		date: '2024-02-15',
		content: 'Full content of the blog post goes here.',
	},
	{
		title: 'The Beauty of Nature',
		intro: 'Nature offers us a sanctuary from the chaos of the modern world...',
		image: 'https://source.unsplash.com/random/400x200?nature',
		author: 'John Doe',
		date: '2024-01-01',
		content: 'Full content of the blog post goes here.',
	},
	{
		title: 'Tech Innovations in 2024',
		intro: 'The tech industry continues to evolve at a rapid pace...',
		image: 'https://source.unsplash.com/random/400x200?tech',
		author: 'Jane Smith',
		date: '2024-02-15',
		content: 'Full content of the blog post goes here.',
	},
	{
		title: 'The Beauty of Nature',
		intro: 'Nature offers us a sanctuary from the chaos of the modern world...',
		image: 'https://source.unsplash.com/random/400x200?nature',
		author: 'John Doe',
		date: '2024-01-01',
		content: 'Full content of the blog post goes here.',
	},
	{
		title: 'Tech Innovations in 2024',
		intro: 'The tech industry continues to evolve at a rapid pace...',
		image: 'https://source.unsplash.com/random/400x200?tech',
		author: 'Jane Smith',
		date: '2024-02-15',
		content: 'Full content of the blog post goes here.',
	},
];
